In [3]:
import numpy as np
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = np.array([[0, 1, 1, 0]]).T

In [16]:
print (training_set_inputs.shape)
print (training_set_inputs)
print (training_set_outputs.shape)

(4, 3)
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
(4, 1)


In [9]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3, 1)) - 1

In [17]:
print (synaptic_weights.shape)
print (synaptic_weights)

(3, 1)
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [28]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [22]:
def sigmoid_derivative(self, x):
        return x * (1 - x)

In [29]:
forward = sigmoid(np.dot(training_set_inputs, synaptic_weights))

In [30]:
print (training_set_inputs.shape)
print (synaptic_weights.shape)
print (forward.shape)
print (forward)

(4, 3)
(3, 1)
(4, 1)
[[0.2689864 ]
 [0.3262757 ]
 [0.23762817]
 [0.36375058]]


In [37]:
W = np.random.random((25, 1))
X = np.random.random((25, 5))

In [40]:
forward = np.dot(W.T, X)

In [41]:
forward

array([[4.36986673, 6.48360195, 5.50932439, 7.13729538, 6.30410647]])