In [195]:
#Imports
import numpy as np

In [218]:
#Load Training Data
#X
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]]).T

#Y
training_set_outputs = np.array([[0, 1, 1, 0]])


#print (training_set_inputs.shape)
#print (training_set_inputs)
#print (training_set_outputs.shape)
#print (training_set_outputs)

(3, 4)
[[0 1 1 0]
 [0 1 0 1]
 [1 1 1 1]]
(1, 4)
[[0 1 1 0]]


In [197]:
#Initialization Function (Weights and Bias)
def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    w = np.zeros((dim,1))
    b = 0

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b


In [219]:
#Activation Function (Sigmoid in this case)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [220]:
def forward_pass_and_backprop(w, b, X, Y):
    """
    Forward pass cost function

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    # Compute Activation
    A = sigmoid(np.dot(w.T,X)+b)                
    #print (A)
    
    # Compute loss (The difference between the desired output and the predicted output)
    # Then sum + extra to produce cost value
    cost = -1 / m * np.sum(Y*np.log(A)+(1-Y)*np.log(1-A), axis = 1, keepdims = True)
    
        
    # BACKWARD PROPAGATION (TO FIND GRAD)
    dw = 1 / m * np.dot(X,(A-Y).T)
    db = 1 / m * np.sum(A-Y)
    
    """
    print ("shape of A = " + str(A.shape))
    print ("shape of Y = " + str(Y.shape))
    print ("m = " + str(m))
    print ("shape of dw = " + str(dw.shape))
    print ("shape of w = " + str(w.shape))
    """
    
    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [221]:
#Unit Test For forward_pass_and_backprop
#cost = 5.801545319394553
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
grads, cost = forward_pass_and_backprop(w, b, X, Y)
print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))
print ("cost = " + str(cost))

dw = [[0.99845601]
 [2.39507239]]
db = 0.001455578136784208
cost = 5.801545319394553


In [222]:
# Train the neural network adjusting the synaptic weights after each epoch
def train(X, Y, number_of_training_iterations, w, b):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron) and compute cost
            grads, cost = forward_pass_and_backprop(w, b, X, Y)

            # Retrieve derivatives from grads
            dw = grads["dw"]
            db = grads["db"]

            # update weights
            w = w - learning_rate * dw
            b = b - learning_rate * db
            
            print (w.T)
        return w,b


In [223]:
#Train the Network (Model)

# Base Hyperparameters
number_of_training_iterations = 10000
learning_rate = 0.002

# initialize parameters
X = training_set_inputs
Y = training_set_outputs
w, b = initialize_with_zeros(X.shape[0])

# Train
w,b = train(X, Y, number_of_training_iterations, w, b)





[[0.0005 0.     0.    ]]
[[ 9.99875000e-04 -6.24999987e-08 -1.24999997e-07]]
[[ 1.49962510e-03 -1.87406238e-07 -3.74828102e-07]]
[[ 1.99925041e-03 -3.74625075e-07 -7.49312627e-07]]
[[ 2.49875102e-03 -6.24062981e-07 -1.24828209e-06]]
[[ 2.99812703e-03 -9.35626539e-07 -1.87156523e-06]]
[[ 3.49737855e-03 -1.30922245e-06 -2.61899095e-06]]
[[ 3.99650568e-03 -1.74475752e-06 -3.49038841e-06]]
[[ 4.49550852e-03 -2.24213869e-06 -4.48558693e-06]]
[[ 4.99438717e-03 -2.80127299e-06 -5.60441606e-06]]
[[ 5.49314173e-03 -3.42206757e-06 -6.84670554e-06]]
[[ 5.99177229e-03 -4.10442971e-06 -8.21228532e-06]]
[[ 6.49027897e-03 -4.84826677e-06 -9.70098556e-06]]
[[ 6.98866187e-03 -5.65348627e-06 -1.13126366e-05]]
[[ 7.48692107e-03 -6.51999580e-06 -1.30470690e-05]]
[[ 7.98505669e-03 -7.44770309e-06 -1.49041136e-05]]
[[ 8.48306882e-03 -8.43651596e-06 -1.68836013e-05]]
[[ 8.98095756e-03 -9.48634237e-06 -1.89853632e-05]]
[[ 9.47872301e-03 -1.05970904e-05 -2.12092307e-05]]
[[ 9.97636528e-03 -1.17686681e-05 -2.35

[[ 0.20738992 -0.00479702 -0.00977651]]
[[ 0.20784369 -0.00481679 -0.00981725]]
[[ 0.20829738 -0.00483659 -0.00985806]]
[[ 0.20875097 -0.00485643 -0.00989893]]
[[ 0.20920447 -0.00487629 -0.00993987]]
[[ 0.20965789 -0.00489619 -0.00998088]]
[[ 0.21011121 -0.00491612 -0.01002195]]
[[ 0.21056445 -0.00493608 -0.01006309]]
[[ 0.21101759 -0.00495606 -0.0101043 ]]
[[ 0.21147065 -0.00497608 -0.01014557]]
[[ 0.21192361 -0.00499613 -0.01018691]]
[[ 0.21237649 -0.00501621 -0.01022832]]
[[ 0.21282928 -0.00503633 -0.01026979]]
[[ 0.21328198 -0.00505647 -0.01031132]]
[[ 0.21373459 -0.00507664 -0.01035293]]
[[ 0.21418711 -0.00509684 -0.01039459]]
[[ 0.21463954 -0.00511707 -0.01043633]]
[[ 0.21509188 -0.00513734 -0.01047813]]
[[ 0.21554414 -0.00515763 -0.01051999]]
[[ 0.2159963  -0.00517795 -0.01056192]]
[[ 0.21644838 -0.00519831 -0.01060392]]
[[ 0.21690037 -0.00521869 -0.01064598]]
[[ 0.21735227 -0.0052391  -0.0106881 ]]
[[ 0.21780408 -0.00525955 -0.01073029]]
[[ 0.2182558  -0.00528002 -0.01077255]]


[[ 0.39957277 -0.01586746 -0.03300685]]
[[ 0.39999207 -0.01589661 -0.03306906]]
[[ 0.40041131 -0.01592578 -0.03313131]]
[[ 0.40083048 -0.01595495 -0.0331936 ]]
[[ 0.40124958 -0.01598414 -0.03325591]]
[[ 0.40166862 -0.01601335 -0.03331826]]
[[ 0.40208758 -0.01604257 -0.03338064]]
[[ 0.40250648 -0.0160718  -0.03344306]]
[[ 0.40292531 -0.01610104 -0.03350551]]
[[ 0.40334407 -0.0161303  -0.03356799]]
[[ 0.40376277 -0.01615956 -0.0336305 ]]
[[ 0.40418139 -0.01618885 -0.03369305]]
[[ 0.40459995 -0.01621814 -0.03375563]]
[[ 0.40501844 -0.01624745 -0.03381825]]
[[ 0.40543686 -0.01627677 -0.03388089]]
[[ 0.40585522 -0.0163061  -0.03394357]]
[[ 0.4062735  -0.01633545 -0.03400629]]
[[ 0.40669172 -0.01636481 -0.03406903]]
[[ 0.40710988 -0.01639418 -0.03413181]]
[[ 0.40752796 -0.01642357 -0.03419462]]
[[ 0.40794598 -0.01645297 -0.03425746]]
[[ 0.40836393 -0.01648238 -0.03432034]]
[[ 0.40878181 -0.0165118  -0.03438325]]
[[ 0.40919962 -0.01654123 -0.03444619]]
[[ 0.40961737 -0.01657068 -0.03450916]]


[[ 0.49347775 -0.02280322 -0.04795865]]
[[ 0.49388239 -0.0228347  -0.0480272 ]]
[[ 0.49428698 -0.02286619 -0.04809578]]
[[ 0.4946915  -0.02289769 -0.04816437]]
[[ 0.49509597 -0.02292919 -0.04823299]]
[[ 0.49550037 -0.0229607  -0.04830164]]
[[ 0.49590471 -0.02299222 -0.0483703 ]]
[[ 0.49630899 -0.02302374 -0.04843899]]
[[ 0.49671321 -0.02305528 -0.04850769]]
[[ 0.49711738 -0.02308682 -0.04857642]]
[[ 0.49752148 -0.02311837 -0.04864518]]
[[ 0.49792552 -0.02314992 -0.04871395]]
[[ 0.4983295  -0.02318148 -0.04878275]]
[[ 0.49873342 -0.02321305 -0.04885157]]
[[ 0.49913727 -0.02324463 -0.04892041]]
[[ 0.49954107 -0.02327622 -0.04898927]]
[[ 0.49994481 -0.02330781 -0.04905816]]
[[ 0.50034849 -0.02333941 -0.04912707]]
[[ 0.50075211 -0.02337101 -0.049196  ]]
[[ 0.50115567 -0.02340263 -0.04926495]]
[[ 0.50155917 -0.02343425 -0.04933392]]
[[ 0.5019626  -0.02346587 -0.04940292]]
[[ 0.50236598 -0.02349751 -0.04947193]]
[[ 0.5027693  -0.02352915 -0.04954097]]
[[ 0.50317256 -0.0235608  -0.04961003]]


[[ 0.68876968 -0.0391081  -0.08432139]]
[[ 0.6891471  -0.03914122 -0.08439706]]
[[ 0.68952446 -0.03917434 -0.08447275]]
[[ 0.68990178 -0.03920745 -0.08454844]]
[[ 0.69027905 -0.03924057 -0.08462414]]
[[ 0.69065627 -0.03927369 -0.08469985]]
[[ 0.69103344 -0.03930681 -0.08477556]]
[[ 0.69141057 -0.03933993 -0.08485128]]
[[ 0.69178764 -0.03937304 -0.08492701]]
[[ 0.69216466 -0.03940616 -0.08500275]]
[[ 0.69254164 -0.03943928 -0.08507849]]
[[ 0.69291856 -0.0394724  -0.08515424]]
[[ 0.69329544 -0.03950551 -0.08523   ]]
[[ 0.69367227 -0.03953863 -0.08530577]]
[[ 0.69404905 -0.03957175 -0.08538154]]
[[ 0.69442578 -0.03960487 -0.08545732]]
[[ 0.69480246 -0.03963798 -0.08553311]]
[[ 0.69517909 -0.0396711  -0.08560891]]
[[ 0.69555567 -0.03970422 -0.08568471]]
[[ 0.69593221 -0.03973733 -0.08576052]]
[[ 0.69630869 -0.03977045 -0.08583634]]
[[ 0.69668513 -0.03980356 -0.08591216]]
[[ 0.69706152 -0.03983668 -0.085988  ]]
[[ 0.69743786 -0.03986979 -0.08606384]]
[[ 0.69781414 -0.03990291 -0.08613968]]


[[ 0.87131385 -0.05545749 -0.12266648]]
[[ 0.87166862 -0.05548961 -0.12274387]]
[[ 0.87202335 -0.05552173 -0.12282127]]
[[ 0.87237804 -0.05555385 -0.12289867]]
[[ 0.87273268 -0.05558596 -0.12297607]]
[[ 0.87308728 -0.05561807 -0.12305347]]
[[ 0.87344184 -0.05565018 -0.12313087]]
[[ 0.87379636 -0.05568228 -0.12320827]]
[[ 0.87415083 -0.05571438 -0.12328567]]
[[ 0.87450526 -0.05574648 -0.12336307]]
[[ 0.87485966 -0.05577857 -0.12344047]]
[[ 0.875214   -0.05581066 -0.12351787]]
[[ 0.87556831 -0.05584274 -0.12359527]]
[[ 0.87592258 -0.05587483 -0.12367267]]
[[ 0.8762768  -0.0559069  -0.12375007]]
[[ 0.87663098 -0.05593898 -0.12382747]]
[[ 0.87698512 -0.05597105 -0.12390488]]
[[ 0.87733922 -0.05600312 -0.12398228]]
[[ 0.87769327 -0.05603518 -0.12405968]]
[[ 0.87804729 -0.05606724 -0.12413708]]
[[ 0.87840126 -0.0560993  -0.12421448]]
[[ 0.87875519 -0.05613135 -0.12429188]]
[[ 0.87910908 -0.0561634  -0.12436928]]
[[ 0.87946293 -0.05619545 -0.12444668]]
[[ 0.87981673 -0.05622749 -0.12452408]]


[[ 0.99230977 -0.06640039 -0.14954769]]
[[ 0.99265055 -0.06643109 -0.14962462]]
[[ 0.99299129 -0.06646178 -0.14970155]]
[[ 0.99333199 -0.06649247 -0.14977847]]
[[ 0.99367265 -0.06652315 -0.14985539]]
[[ 0.99401327 -0.06655383 -0.14993231]]
[[ 0.99435385 -0.06658451 -0.15000922]]
[[ 0.9946944  -0.06661518 -0.15008614]]
[[ 0.9950349  -0.06664585 -0.15016305]]
[[ 0.99537537 -0.06667651 -0.15023995]]
[[ 0.9957158  -0.06670716 -0.15031686]]
[[ 0.99605619 -0.06673782 -0.15039376]]
[[ 0.99639655 -0.06676846 -0.15047066]]
[[ 0.99673686 -0.06679911 -0.15054756]]
[[ 0.99707714 -0.06682975 -0.15062445]]
[[ 0.99741737 -0.06686038 -0.15070134]]
[[ 0.99775757 -0.06689101 -0.15077823]]
[[ 0.99809773 -0.06692163 -0.15085511]]
[[ 0.99843786 -0.06695225 -0.150932  ]]
[[ 0.99877794 -0.06698287 -0.15100888]]
[[ 0.99911799 -0.06701348 -0.15108575]]
[[ 0.99945799 -0.06704409 -0.15116263]]
[[ 0.99979796 -0.06707469 -0.1512395 ]]
[[ 1.0001379  -0.06710528 -0.15131637]]
[[ 1.00047779 -0.06713588 -0.15139324]]


[[ 1.06470534 -0.07289186 -0.16601769]]
[[ 1.06503804 -0.07292153 -0.16609393]]
[[ 1.0653707  -0.0729512  -0.16617017]]
[[ 1.06570333 -0.07298086 -0.1662464 ]]
[[ 1.06603592 -0.07301051 -0.16632262]]
[[ 1.06636847 -0.07304016 -0.16639885]]
[[ 1.06670099 -0.07306981 -0.16647507]]
[[ 1.06703347 -0.07309945 -0.16655128]]
[[ 1.06736591 -0.07312908 -0.16662749]]
[[ 1.06769832 -0.07315871 -0.1667037 ]]
[[ 1.06803069 -0.07318834 -0.16677991]]
[[ 1.06836302 -0.07321796 -0.16685611]]
[[ 1.06869532 -0.07324757 -0.1669323 ]]
[[ 1.06902758 -0.07327718 -0.1670085 ]]
[[ 1.0693598  -0.07330679 -0.16708468]]
[[ 1.06969199 -0.07333639 -0.16716087]]
[[ 1.07002414 -0.07336598 -0.16723705]]
[[ 1.07035625 -0.07339557 -0.16731323]]
[[ 1.07068833 -0.07342516 -0.1673894 ]]
[[ 1.07102037 -0.07345474 -0.16746557]]
[[ 1.07135237 -0.07348432 -0.16754174]]
[[ 1.07168434 -0.07351389 -0.1676179 ]]
[[ 1.07201627 -0.07354345 -0.16769406]]
[[ 1.07234816 -0.07357301 -0.16777021]]
[[ 1.07268002 -0.07360257 -0.16784637]]


[[ 1.15128842 -0.08054977 -0.18600299]]
[[ 1.1516117  -0.0805781  -0.18607811]]
[[ 1.15193495 -0.08060643 -0.18615322]]
[[ 1.15225817 -0.08063475 -0.18622833]]
[[ 1.15258135 -0.08066306 -0.18630344]]
[[ 1.15290449 -0.08069137 -0.18637854]]
[[ 1.1532276  -0.08071967 -0.18645364]]
[[ 1.15355068 -0.08074797 -0.18652873]]
[[ 1.15387372 -0.08077627 -0.18660382]]
[[ 1.15419673 -0.08080456 -0.18667891]]
[[ 1.1545197  -0.08083284 -0.18675399]]
[[ 1.15484264 -0.08086112 -0.18682906]]
[[ 1.15516554 -0.08088939 -0.18690413]]
[[ 1.15548841 -0.08091766 -0.18697919]]
[[ 1.15581124 -0.08094592 -0.18705425]]
[[ 1.15613404 -0.08097418 -0.18712931]]
[[ 1.1564568  -0.08100243 -0.18720436]]
[[ 1.15677953 -0.08103068 -0.18727941]]
[[ 1.15710223 -0.08105892 -0.18735445]]
[[ 1.15742489 -0.08108716 -0.18742948]]
[[ 1.15774751 -0.08111539 -0.18750452]]
[[ 1.1580701  -0.08114362 -0.18757954]]
[[ 1.15839266 -0.08117184 -0.18765457]]
[[ 1.15871518 -0.08120005 -0.18772958]]
[[ 1.15903767 -0.08122827 -0.1878046 ]]


[[ 1.31394799 -0.09450287 -0.22416822]]
[[ 1.3142542  -0.09452851 -0.22424066]]
[[ 1.31456037 -0.09455415 -0.22431309]]
[[ 1.31486651 -0.09457978 -0.22438552]]
[[ 1.31517262 -0.09460541 -0.22445794]]
[[ 1.3154787  -0.09463104 -0.22453035]]
[[ 1.31578474 -0.09465665 -0.22460276]]
[[ 1.31609076 -0.09468227 -0.22467517]]
[[ 1.31639674 -0.09470787 -0.22474757]]
[[ 1.31670269 -0.09473348 -0.22481996]]
[[ 1.31700861 -0.09475907 -0.22489235]]
[[ 1.3173145  -0.09478467 -0.22496473]]
[[ 1.31762036 -0.09481025 -0.22503711]]
[[ 1.31792619 -0.09483584 -0.22510948]]
[[ 1.31823198 -0.09486141 -0.22518185]]
[[ 1.31853775 -0.09488699 -0.22525421]]
[[ 1.31884348 -0.09491255 -0.22532656]]
[[ 1.31914918 -0.09493811 -0.22539891]]
[[ 1.31945485 -0.09496367 -0.22547125]]
[[ 1.31976049 -0.09498922 -0.22554359]]
[[ 1.32006609 -0.09501477 -0.22561592]]
[[ 1.32037167 -0.09504031 -0.22568825]]
[[ 1.32067721 -0.09506585 -0.22576057]]
[[ 1.32098272 -0.09509138 -0.22583289]]
[[ 1.3212882  -0.0951169  -0.22590519]]


[[ 1.45185719 -0.10578718 -0.25696091]]
[[ 1.45214944 -0.10581051 -0.25703071]]
[[ 1.45244167 -0.10583383 -0.25710051]]
[[ 1.45273387 -0.10585715 -0.25717031]]
[[ 1.45302603 -0.10588047 -0.2572401 ]]
[[ 1.45331817 -0.10590377 -0.25730988]]
[[ 1.45361028 -0.10592708 -0.25737966]]
[[ 1.45390236 -0.10595038 -0.25744943]]
[[ 1.45419441 -0.10597367 -0.2575192 ]]
[[ 1.45448643 -0.10599696 -0.25758896]]
[[ 1.45477843 -0.10602025 -0.25765871]]
[[ 1.45507039 -0.10604353 -0.25772846]]
[[ 1.45536232 -0.1060668  -0.25779821]]
[[ 1.45565423 -0.10609007 -0.25786794]]
[[ 1.45594611 -0.10611334 -0.25793767]]
[[ 1.45623795 -0.1061366  -0.2580074 ]]
[[ 1.45652977 -0.10615985 -0.25807712]]
[[ 1.45682156 -0.1061831  -0.25814683]]
[[ 1.45711332 -0.10620635 -0.25821654]]
[[ 1.45740505 -0.10622959 -0.25828625]]
[[ 1.45769676 -0.10625282 -0.25835594]]
[[ 1.45798843 -0.10627605 -0.25842563]]
[[ 1.45828007 -0.10629928 -0.25849532]]
[[ 1.45857169 -0.1063225  -0.258565  ]]
[[ 1.45886328 -0.10634572 -0.25863467]]


[[ 1.59973501 -0.11725817 -0.29241283]]
[[ 1.60001279 -0.11727908 -0.29247964]]
[[ 1.60029054 -0.11729998 -0.29254644]]
[[ 1.60056826 -0.11732088 -0.29261324]]
[[ 1.60084596 -0.11734178 -0.29268003]]
[[ 1.60112363 -0.11736267 -0.29274682]]
[[ 1.60140127 -0.11738355 -0.2928136 ]]
[[ 1.60167888 -0.11740444 -0.29288038]]
[[ 1.60195647 -0.11742531 -0.29294715]]
[[ 1.60223404 -0.11744619 -0.29301391]]
[[ 1.60251157 -0.11746705 -0.29308067]]
[[ 1.60278908 -0.11748792 -0.29314742]]
[[ 1.60306657 -0.11750878 -0.29321417]]
[[ 1.60334402 -0.11752963 -0.29328091]]
[[ 1.60362145 -0.11755048 -0.29334765]]
[[ 1.60389885 -0.11757133 -0.29341438]]
[[ 1.60417623 -0.11759217 -0.2934811 ]]
[[ 1.60445358 -0.11761301 -0.29354782]]
[[ 1.6047309  -0.11763384 -0.29361453]]
[[ 1.6050082  -0.11765467 -0.29368124]]
[[ 1.60528547 -0.1176755  -0.29374794]]
[[ 1.60556271 -0.11769632 -0.29381463]]
[[ 1.60583993 -0.11771713 -0.29388132]]
[[ 1.60611712 -0.11773794 -0.29394801]]
[[ 1.60639428 -0.11775875 -0.29401469]]


[[ 1.65884846 -0.12165274 -0.30664594]]
[[ 1.65912058 -0.12167272 -0.30671152]]
[[ 1.65939268 -0.12169269 -0.30677711]]
[[ 1.65966475 -0.12171265 -0.30684268]]
[[ 1.65993679 -0.12173261 -0.30690826]]
[[ 1.66020881 -0.12175257 -0.30697382]]
[[ 1.6604808  -0.12177252 -0.30703938]]
[[ 1.66075277 -0.12179247 -0.30710494]]
[[ 1.66102471 -0.12181241 -0.30717049]]
[[ 1.66129662 -0.12183235 -0.30723603]]
[[ 1.66156851 -0.12185229 -0.30730157]]
[[ 1.66184037 -0.12187222 -0.3073671 ]]
[[ 1.66211221 -0.12189215 -0.30743263]]
[[ 1.66238402 -0.12191207 -0.30749815]]
[[ 1.66265581 -0.12193199 -0.30756366]]
[[ 1.66292757 -0.1219519  -0.30762917]]
[[ 1.6631993  -0.12197181 -0.30769467]]
[[ 1.66347101 -0.12199172 -0.30776017]]
[[ 1.66374269 -0.12201162 -0.30782567]]
[[ 1.66401435 -0.12203152 -0.30789115]]
[[ 1.66428598 -0.12205141 -0.30795663]]
[[ 1.66455758 -0.1220713  -0.30802211]]
[[ 1.66482916 -0.12209118 -0.30808758]]
[[ 1.66510071 -0.12211107 -0.30815304]]
[[ 1.66537224 -0.12213094 -0.3082185 ]]


[[ 1.738284   -0.12738312 -0.32581594]]
[[ 1.73854864 -0.12740187 -0.32587988]]
[[ 1.73881325 -0.12742062 -0.32594382]]
[[ 1.73907784 -0.12743937 -0.32600774]]
[[ 1.7393424  -0.12745811 -0.32607167]]
[[ 1.73960694 -0.12747685 -0.32613559]]
[[ 1.73987145 -0.12749558 -0.3261995 ]]
[[ 1.74013594 -0.12751431 -0.32626341]]
[[ 1.74040041 -0.12753304 -0.32632731]]
[[ 1.74066485 -0.12755176 -0.3263912 ]]
[[ 1.74092926 -0.12757048 -0.3264551 ]]
[[ 1.74119365 -0.12758919 -0.32651898]]
[[ 1.74145802 -0.1276079  -0.32658286]]
[[ 1.74172236 -0.12762661 -0.32664673]]
[[ 1.74198667 -0.12764531 -0.3267106 ]]
[[ 1.74225096 -0.12766401 -0.32677447]]
[[ 1.74251523 -0.1276827  -0.32683832]]
[[ 1.74277947 -0.12770139 -0.32690218]]
[[ 1.74304369 -0.12772008 -0.32696602]]
[[ 1.74330788 -0.12773876 -0.32702986]]
[[ 1.74357205 -0.12775744 -0.3270937 ]]
[[ 1.74383619 -0.12777611 -0.32715753]]
[[ 1.74410031 -0.12779478 -0.32722136]]
[[ 1.74436441 -0.12781345 -0.32728518]]
[[ 1.74462848 -0.12783211 -0.32734899]]


[[ 1.80600989 -0.13210954 -0.34219442]]
[[ 1.80626825 -0.13212729 -0.34225695]]
[[ 1.80652658 -0.13214503 -0.34231948]]
[[ 1.80678489 -0.13216278 -0.34238201]]
[[ 1.80704318 -0.13218051 -0.34244453]]
[[ 1.80730145 -0.13219825 -0.34250704]]
[[ 1.80755969 -0.13221598 -0.34256955]]
[[ 1.80781791 -0.13223371 -0.34263205]]
[[ 1.8080761  -0.13225143 -0.34269455]]
[[ 1.80833427 -0.13226915 -0.34275704]]
[[ 1.80859241 -0.13228686 -0.34281953]]
[[ 1.80885054 -0.13230458 -0.34288201]]
[[ 1.80910864 -0.13232228 -0.34294449]]
[[ 1.80936671 -0.13233999 -0.34300696]]
[[ 1.80962476 -0.13235769 -0.34306942]]
[[ 1.80988279 -0.13237539 -0.34313188]]
[[ 1.81014079 -0.13239308 -0.34319434]]
[[ 1.81039877 -0.13241077 -0.34325679]]
[[ 1.81065673 -0.13242845 -0.34331923]]
[[ 1.81091466 -0.13244614 -0.34338167]]
[[ 1.81117257 -0.13246381 -0.34344411]]
[[ 1.81143045 -0.13248149 -0.34350654]]
[[ 1.81168832 -0.13249916 -0.34356896]]
[[ 1.81194615 -0.13251682 -0.34363138]]
[[ 1.81220397 -0.13253449 -0.34369379]]


[[ 1.90749442 -0.13891774 -0.3667877 ]]
[[ 1.90774356 -0.13893405 -0.36684815]]
[[ 1.90799266 -0.13895035 -0.36690858]]
[[ 1.90824175 -0.13896666 -0.36696901]]
[[ 1.90849082 -0.13898296 -0.36702944]]
[[ 1.90873986 -0.13899925 -0.36708986]]
[[ 1.90898888 -0.13901554 -0.36715028]]
[[ 1.90923787 -0.13903183 -0.36721069]]
[[ 1.90948685 -0.13904812 -0.36727109]]
[[ 1.9097358 -0.1390644 -0.3673315]]
[[ 1.90998473 -0.13908068 -0.36739189]]
[[ 1.91023364 -0.13909696 -0.36745228]]
[[ 1.91048252 -0.13911323 -0.36751267]]
[[ 1.91073139 -0.1391295  -0.36757305]]
[[ 1.91098023 -0.13914576 -0.36763342]]
[[ 1.91122905 -0.13916203 -0.36769379]]
[[ 1.91147784 -0.13917829 -0.36775416]]
[[ 1.91172662 -0.13919454 -0.36781452]]
[[ 1.91197537 -0.13921079 -0.36787487]]
[[ 1.9122241  -0.13922704 -0.36793522]]
[[ 1.9124728  -0.13924329 -0.36799557]]
[[ 1.91272149 -0.13925953 -0.36805591]]
[[ 1.91297015 -0.13927577 -0.36811624]]
[[ 1.91321879 -0.139292   -0.36817657]]
[[ 1.91346741 -0.13930823 -0.36823689]]
[[ 

[[ 2.02909528 -0.14664594 -0.39632521]]
[[ 2.02933363 -0.14666063 -0.39638318]]
[[ 2.02957197 -0.14667532 -0.39644114]]
[[ 2.02981028 -0.14669001 -0.39649909]]
[[ 2.03004858 -0.14670469 -0.39655705]]
[[ 2.03028685 -0.14671937 -0.39661499]]
[[ 2.0305251  -0.14673405 -0.39667293]]
[[ 2.03076333 -0.14674872 -0.39673087]]
[[ 2.03100154 -0.1467634  -0.3967888 ]]
[[ 2.03123973 -0.14677807 -0.39684673]]
[[ 2.0314779  -0.14679273 -0.39690465]]
[[ 2.03171605 -0.14680739 -0.39696257]]
[[ 2.03195417 -0.14682205 -0.39702048]]
[[ 2.03219228 -0.14683671 -0.39707839]]
[[ 2.03243037 -0.14685136 -0.39713629]]
[[ 2.03266843 -0.14686601 -0.39719419]]
[[ 2.03290647 -0.14688066 -0.39725208]]
[[ 2.0331445  -0.14689531 -0.39730997]]
[[ 2.0333825  -0.14690995 -0.39736785]]
[[ 2.03362048 -0.14692459 -0.39742573]]
[[ 2.03385844 -0.14693922 -0.39748361]]
[[ 2.03409638 -0.14695385 -0.39754148]]
[[ 2.0343343  -0.14696848 -0.39759934]]
[[ 2.0345722  -0.14698311 -0.3976572 ]]
[[ 2.03481008 -0.14699773 -0.39771506]]


[[ 2.1126564  -0.15168913 -0.4166614 ]]
[[ 2.11288753 -0.15170278 -0.4167177 ]]
[[ 2.11311864 -0.15171643 -0.41677398]]
[[ 2.11334973 -0.15173008 -0.41683026]]
[[ 2.1135808  -0.15174372 -0.41688654]]
[[ 2.11381185 -0.15175736 -0.41694281]]
[[ 2.11404288 -0.151771   -0.41699908]]
[[ 2.11427389 -0.15178463 -0.41705534]]
[[ 2.11450489 -0.15179826 -0.4171116 ]]
[[ 2.11473586 -0.15181189 -0.41716786]]
[[ 2.11496681 -0.15182552 -0.41722411]]
[[ 2.11519774 -0.15183914 -0.41728035]]
[[ 2.11542865 -0.15185276 -0.41733659]]
[[ 2.11565955 -0.15186638 -0.41739283]]
[[ 2.11589042 -0.15187999 -0.41744906]]
[[ 2.11612127 -0.15189361 -0.41750528]]
[[ 2.11635211 -0.15190722 -0.41756151]]
[[ 2.11658292 -0.15192082 -0.41761772]]
[[ 2.11681371 -0.15193443 -0.41767394]]
[[ 2.11704449 -0.15194803 -0.41773014]]
[[ 2.11727524 -0.15196162 -0.41778635]]
[[ 2.11750598 -0.15197522 -0.41784255]]
[[ 2.11773669 -0.15198881 -0.41789874]]
[[ 2.11796739 -0.1520024  -0.41795493]]
[[ 2.11819806 -0.15201599 -0.41801112]]


[[ 2.25731013 -0.15991645 -0.45193305]]
[[ 2.2575291  -0.15992843 -0.45198651]]
[[ 2.25774805 -0.15994041 -0.45203996]]
[[ 2.25796698 -0.15995238 -0.4520934 ]]
[[ 2.2581859  -0.15996436 -0.45214684]]
[[ 2.25840479 -0.15997633 -0.45220028]]
[[ 2.25862367 -0.15998829 -0.45225371]]
[[ 2.25884253 -0.16000026 -0.45230714]]
[[ 2.25906137 -0.16001222 -0.45236056]]
[[ 2.2592802  -0.16002418 -0.45241398]]
[[ 2.259499   -0.16003614 -0.4524674 ]]
[[ 2.25971779 -0.16004809 -0.45252081]]
[[ 2.25993656 -0.16006005 -0.45257422]]
[[ 2.26015531 -0.160072   -0.45262762]]
[[ 2.26037405 -0.16008394 -0.45268102]]
[[ 2.26059276 -0.16009589 -0.45273441]]
[[ 2.26081146 -0.16010783 -0.4527878 ]]
[[ 2.26103014 -0.16011977 -0.45284119]]
[[ 2.2612488  -0.16013171 -0.45289457]]
[[ 2.26146744 -0.16014365 -0.45294795]]
[[ 2.26168607 -0.16015558 -0.45300132]]
[[ 2.26190467 -0.16016751 -0.45305469]]
[[ 2.26212326 -0.16017944 -0.45310806]]
[[ 2.26234183 -0.16019137 -0.45316142]]
[[ 2.26256039 -0.16020329 -0.45321477]]


[[ 2.3643801  -0.16560661 -0.47809184]]
[[ 2.36459035 -0.16561746 -0.47814325]]
[[ 2.36480059 -0.1656283  -0.47819466]]
[[ 2.36501081 -0.16563914 -0.47824606]]
[[ 2.36522101 -0.16564998 -0.47829746]]
[[ 2.36543119 -0.16566082 -0.47834885]]
[[ 2.36564136 -0.16567166 -0.47840024]]
[[ 2.36585151 -0.16568249 -0.47845162]]
[[ 2.36606165 -0.16569332 -0.47850301]]
[[ 2.36627176 -0.16570415 -0.47855438]]
[[ 2.36648186 -0.16571498 -0.47860576]]
[[ 2.36669195 -0.16572581 -0.47865713]]
[[ 2.36690201 -0.16573663 -0.47870849]]
[[ 2.36711206 -0.16574745 -0.47875985]]
[[ 2.3673221  -0.16575827 -0.47881121]]
[[ 2.36753211 -0.16576909 -0.47886256]]
[[ 2.36774211 -0.1657799  -0.47891391]]
[[ 2.36795209 -0.16579072 -0.47896526]]
[[ 2.36816206 -0.16580153 -0.4790166 ]]
[[ 2.36837201 -0.16581233 -0.47906794]]
[[ 2.36858194 -0.16582314 -0.47911927]]
[[ 2.36879186 -0.16583395 -0.4791706 ]]
[[ 2.36900175 -0.16584475 -0.47922193]]
[[ 2.36921163 -0.16585555 -0.47927325]]
[[ 2.3694215  -0.16586635 -0.47932457]]


[[ 2.4674475  -0.17077345 -0.50331192]]
[[ 2.46764959 -0.17078329 -0.50336141]]
[[ 2.46785167 -0.17079312 -0.50341089]]
[[ 2.46805373 -0.17080296 -0.50346037]]
[[ 2.46825577 -0.17081279 -0.50350985]]
[[ 2.4684578  -0.17082262 -0.50355932]]
[[ 2.46865982 -0.17083245 -0.50360879]]
[[ 2.46886181 -0.17084228 -0.50365826]]
[[ 2.4690638  -0.1708521  -0.50370772]]
[[ 2.46926576 -0.17086192 -0.50375718]]
[[ 2.46946771 -0.17087174 -0.50380663]]
[[ 2.46966965 -0.17088156 -0.50385608]]
[[ 2.46987157 -0.17089138 -0.50390553]]
[[ 2.47007347 -0.1709012  -0.50395498]]
[[ 2.47027536 -0.17091101 -0.50400441]]
[[ 2.47047723 -0.17092082 -0.50405385]]
[[ 2.47067909 -0.17093063 -0.50410328]]
[[ 2.47088093 -0.17094044 -0.50415271]]
[[ 2.47108276 -0.17095024 -0.50420214]]
[[ 2.47128456 -0.17096005 -0.50425156]]
[[ 2.47148636 -0.17096985 -0.50430097]]
[[ 2.47168814 -0.17097965 -0.50435039]]
[[ 2.4718899  -0.17098945 -0.5043998 ]]
[[ 2.47209164 -0.17099924 -0.5044492 ]]
[[ 2.47229337 -0.17100904 -0.50449861]]


[[ 2.56637419 -0.17545515 -0.52755371]]
[[ 2.56656866 -0.17546409 -0.5276014 ]]
[[ 2.56676312 -0.17547303 -0.52764909]]
[[ 2.56695757 -0.17548197 -0.52769677]]
[[ 2.567152   -0.17549091 -0.52774445]]
[[ 2.56734642 -0.17549984 -0.52779212]]
[[ 2.56754082 -0.17550877 -0.52783979]]
[[ 2.5677352  -0.1755177  -0.52788746]]
[[ 2.56792958 -0.17552663 -0.52793512]]
[[ 2.56812393 -0.17553556 -0.52798279]]
[[ 2.56831828 -0.17554449 -0.52803044]]
[[ 2.5685126  -0.17555341 -0.5280781 ]]
[[ 2.56870692 -0.17556234 -0.52812575]]
[[ 2.56890121 -0.17557126 -0.52817339]]
[[ 2.5690955  -0.17558018 -0.52822104]]
[[ 2.56928977 -0.1755891  -0.52826868]]
[[ 2.56948402 -0.17559801 -0.52831631]]
[[ 2.56967826 -0.17560693 -0.52836395]]
[[ 2.56987249 -0.17561584 -0.52841158]]
[[ 2.5700667  -0.17562475 -0.5284592 ]]
[[ 2.57026089 -0.17563366 -0.52850683]]
[[ 2.57045507 -0.17564257 -0.52855444]]
[[ 2.57064924 -0.17565147 -0.52860206]]
[[ 2.57084339 -0.17566038 -0.52864967]]
[[ 2.57103752 -0.17566928 -0.52869728]]


[[ 2.6576841  -0.17954283 -0.54995856]]
[[ 2.65787173 -0.179551   -0.55000463]]
[[ 2.65805935 -0.17955917 -0.55005069]]
[[ 2.65824695 -0.17956734 -0.55009675]]
[[ 2.65843454 -0.17957551 -0.55014281]]
[[ 2.65862212 -0.17958368 -0.55018887]]
[[ 2.65880968 -0.17959185 -0.55023492]]
[[ 2.65899723 -0.17960001 -0.55028097]]
[[ 2.65918476 -0.17960818 -0.55032701]]
[[ 2.65937228 -0.17961634 -0.55037305]]
[[ 2.65955979 -0.1796245  -0.55041909]]
[[ 2.65974728 -0.17963266 -0.55046513]]
[[ 2.65993476 -0.17964081 -0.55051116]]
[[ 2.66012222 -0.17964897 -0.55055719]]
[[ 2.66030967 -0.17965712 -0.55060321]]
[[ 2.66049711 -0.17966528 -0.55064923]]
[[ 2.66068453 -0.17967343 -0.55069525]]
[[ 2.66087194 -0.17968158 -0.55074127]]
[[ 2.66105934 -0.17968972 -0.55078728]]
[[ 2.66124672 -0.17969787 -0.55083329]]
[[ 2.66143408 -0.17970602 -0.55087929]]
[[ 2.66162144 -0.17971416 -0.5509253 ]]
[[ 2.66180878 -0.1797223  -0.5509713 ]]
[[ 2.6619961  -0.17973044 -0.55101729]]
[[ 2.66218342 -0.17973858 -0.55106328]]


[[ 2.72215378 -0.18229788 -0.56579429]]
[[ 2.72233669 -0.18230554 -0.56583923]]
[[ 2.72251958 -0.1823132  -0.56588418]]
[[ 2.72270246 -0.18232087 -0.56592912]]
[[ 2.72288533 -0.18232853 -0.56597405]]
[[ 2.72306818 -0.18233619 -0.56601899]]
[[ 2.72325102 -0.18234384 -0.56606392]]
[[ 2.72343385 -0.1823515  -0.56610885]]
[[ 2.72361666 -0.18235916 -0.56615377]]
[[ 2.72379946 -0.18236681 -0.56619869]]
[[ 2.72398225 -0.18237446 -0.56624361]]
[[ 2.72416502 -0.18238211 -0.56628853]]
[[ 2.72434778 -0.18238976 -0.56633344]]
[[ 2.72453053 -0.18239741 -0.56637835]]
[[ 2.72471326 -0.18240506 -0.56642325]]
[[ 2.72489598 -0.1824127  -0.56646815]]
[[ 2.72507869 -0.18242035 -0.56651305]]
[[ 2.72526138 -0.18242799 -0.56655795]]
[[ 2.72544406 -0.18243563 -0.56660284]]
[[ 2.72562673 -0.18244327 -0.56664773]]
[[ 2.72580938 -0.18245091 -0.56669262]]
[[ 2.72599202 -0.18245854 -0.5667375 ]]
[[ 2.72617465 -0.18246618 -0.56678238]]
[[ 2.72635726 -0.18247381 -0.56682726]]
[[ 2.72653987 -0.18248145 -0.56687214]]


[[ 2.77858455 -0.18462263 -0.57966655]]
[[ 2.7787634  -0.18462987 -0.57971053]]
[[ 2.77894223 -0.18463711 -0.57975451]]
[[ 2.77912104 -0.18464434 -0.57979849]]
[[ 2.77929985 -0.18465158 -0.57984246]]
[[ 2.77947864 -0.18465882 -0.57988643]]
[[ 2.77965742 -0.18466605 -0.57993039]]
[[ 2.77983619 -0.18467328 -0.57997436]]
[[ 2.78001494 -0.18468052 -0.58001832]]
[[ 2.78019368 -0.18468775 -0.58006227]]
[[ 2.78037241 -0.18469498 -0.58010623]]
[[ 2.78055113 -0.1847022  -0.58015018]]
[[ 2.78072983 -0.18470943 -0.58019413]]
[[ 2.78090852 -0.18471666 -0.58023807]]
[[ 2.7810872  -0.18472388 -0.58028201]]
[[ 2.78126586 -0.1847311  -0.58032595]]
[[ 2.78144451 -0.18473832 -0.58036989]]
[[ 2.78162315 -0.18474554 -0.58041382]]
[[ 2.78180178 -0.18475276 -0.58045775]]
[[ 2.78198039 -0.18475998 -0.58050168]]
[[ 2.78215899 -0.18476719 -0.5805456 ]]
[[ 2.78233758 -0.18477441 -0.58058952]]
[[ 2.78251616 -0.18478162 -0.58063344]]
[[ 2.78269472 -0.18478884 -0.58067735]]
[[ 2.78287327 -0.18479605 -0.58072126]]


In [224]:
#Try a Test Value
print ("Considering new situation [1, 0, 0] -> ?: ")
test = np.array([1, 0, 0])
yhat = sigmoid(np.dot(w.T,test)+b)
print (np.where(yhat>0.5,1,0))

Considering new situation [1, 0, 0] -> ?: 
[1]
