In [1]:
#Imports
import numpy as np

In [4]:
#Load Training Data
#X
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])

#Y
training_set_outputs = np.array([[0, 1, 1, 0]])


print (training_set_inputs.shape)
print (training_set_inputs)
print (training_set_outputs.shape)
print (training_set_outputs.T)

(4, 3)
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
(1, 4)
[[0]
 [1]
 [1]
 [0]]


In [5]:
#Initialization Function (Weights and Bias)
def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    w = np.zeros((dim,1))
    b = 0

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b


In [6]:
#Activation Function (Sigmoid in this case)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [15]:
def forward_pass_and_backprop(w, b, X, Y):
    """
    Forward pass cost function

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    # Compute Activation
    A = sigmoid(np.dot(w,X)+b)                
    #print (A)
    
    # Compute loss (The difference between the desired output and the predicted output)
    # Then sum + extra to produce cost value
    cost = -1 / m * np.sum(Y*np.log(A)+(1-Y)*np.log(1-A), axis = 1, keepdims = True)
    
        
    # BACKWARD PROPAGATION (TO FIND GRAD)
    dw = 1 / m * np.dot(X,(A-Y).T)
    db = 1 / m * np.sum(A-Y)
    
    """
    print ("shape of A = " + str(A.shape))
    print ("shape of Y = " + str(Y.shape))
    print ("m = " + str(m))
    print ("shape of dw = " + str(dw.shape))
    print ("shape of w = " + str(w.shape))
    """
    
    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [8]:
#Unit Test For forward_pass_and_backprop
#cost = 5.801545319394553
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
grads, cost = forward_pass_and_backprop(w, b, X, Y)
print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))
print ("cost = " + str(cost))

dw = [[0.99845601]
 [2.39507239]]
db = 0.001455578136784208
cost = 5.801545319394553


In [9]:
# Train the neural network adjusting the synaptic weights after each epoch
def train(X, Y, number_of_training_iterations, w, b):
        
        print_cost = True
        costs = []
        
        for iteration in range(number_of_training_iterations):
        
            # Pass the training set through our neural network (a single neuron) and compute cost
            grads, cost = forward_pass_and_backprop(w, b, X, Y)

            # Retrieve derivatives from grads
            dw = grads["dw"]
            db = grads["db"]

            # update weights
            w = w - learning_rate * dw
            b = b - learning_rate * db
            
            
            # Record the costs
            if iteration % 100 == 0:
                costs.append(cost)
        
            # Print the cost every 100 training iterations
            if print_cost and iteration % 100 == 0:
                print ("Cost after iteration %i: %f" %(iteration, cost))
            
            
            #print (w.T)
                        
        return w,b


In [16]:
#Train the Network (Model)

# Base Hyperparameters
number_of_training_iterations = 10
learning_rate = 0.002

# initialize parameters
X = training_set_inputs
Y = training_set_outputs
w, b = initialize_with_zeros(X.shape[1])

print (X.shape) 
print (w.T.shape)

# Train
w,b = train(X, Y, number_of_training_iterations, w, b)





(4, 3)
(1, 3)


ValueError: shapes (3,1) and (4,3) not aligned: 1 (dim 1) != 4 (dim 0)

In [ ]:
#Try a Test Value
print ("Considering new situation [1, 0, 0] -> ?: ")
test = np.array([1, 0, 0])
yhat = sigmoid(np.dot(w.T,test)+b)
print (np.where(yhat>0.5,1,0))