In [1]:
#Imports
import numpy as np

In [2]:
#Load Training Data
#X
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]]).T

#Y
training_set_outputs = np.array([[0, 1, 1, 0]])


#print (training_set_inputs.shape)
#print (training_set_inputs)
#print (training_set_outputs.shape)
#print (training_set_outputs)

In [3]:
#Initialization Function (Weights and Bias)
def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    w = np.zeros((dim,1))
    b = 0

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b


In [4]:
#Activation Function (Sigmoid in this case)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
def forward_pass_and_backprop(w, b, X, Y):
    """
    Forward pass cost function

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    # Compute Activation
    A = sigmoid(np.dot(w.T,X)+b)                
    #print (A)
    
    # Compute loss (The difference between the desired output and the predicted output)
    # Then sum + extra to produce cost value
    cost = -1 / m * np.sum(Y*np.log(A)+(1-Y)*np.log(1-A), axis = 1, keepdims = True)
    
        
    # BACKWARD PROPAGATION (TO FIND GRAD)
    dw = 1 / m * np.dot(X,(A-Y).T)
    db = 1 / m * np.sum(A-Y)
    
    """
    print ("shape of A = " + str(A.shape))
    print ("shape of Y = " + str(Y.shape))
    print ("m = " + str(m))
    print ("shape of dw = " + str(dw.shape))
    print ("shape of w = " + str(w.shape))
    """
    
    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [6]:
#Unit Test For forward_pass_and_backprop
#cost = 5.801545319394553
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
grads, cost = forward_pass_and_backprop(w, b, X, Y)
print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))
print ("cost = " + str(cost))

dw = [[0.99845601]
 [2.39507239]]
db = 0.001455578136784208
cost = 5.801545319394553


In [7]:
# Train the neural network adjusting the synaptic weights after each epoch
def train(X, Y, number_of_training_iterations, w, b):
        
        print_cost = True
        costs = []
        
        print (w)
        
        for iteration in range(number_of_training_iterations):
        
            # Pass the training set through our neural network (a single neuron) and compute cost
            grads, cost = forward_pass_and_backprop(w, b, X, Y)

            # Retrieve derivatives from grads
            dw = grads["dw"]
            db = grads["db"]

            # update weights
            w = w - learning_rate * dw
            b = b - learning_rate * db
            
            
            # Record the costs
            if iteration % 100 == 0:
                costs.append(cost)
        
            # Print the cost every 100 training iterations
            #if print_cost and iteration % 100 == 0:
            if print_cost and iteration % 1000 == 0:
                print ("Cost after iteration %i: %f" %(iteration, cost))
                print (w)
            
            #print (w.T)
                        
        return w,b


In [8]:
#Train the Network (Model)

# Base Hyperparameters
number_of_training_iterations = 1000000 #10000
learning_rate = 0.002

# initialize parameters
X = training_set_inputs
Y = training_set_outputs
w, b = initialize_with_zeros(X.shape[0])

# Train
w,b = train(X, Y, number_of_training_iterations, w, b)





[[0.]
 [0.]
 [0.]]
Cost after iteration 0: 0.693147
[[0.0005]
 [0.    ]
 [0.    ]]
Cost after iteration 1000: 0.589037
[[ 0.45105767]
 [-0.01957435]
 [-0.04096066]]
Cost after iteration 2000: 0.509403
[[ 0.83454513]
 [-0.05213091]
 [-0.11469718]]
Cost after iteration 3000: 0.445449
[[ 1.17383487]
 [-0.08252037]
 [-0.19125005]]
Cost after iteration 4000: 0.393427
[[ 1.47862342]
 [-0.10791309]
 [-0.26335889]]
Cost after iteration 5000: 0.350671
[[ 1.7546449 ]
 [-0.12853834]
 [-0.32976986]]
Cost after iteration 6000: 0.315167
[[ 2.00611573]
 [-0.14522107]
 [-0.39073804]]
Cost after iteration 7000: 0.285385
[[ 2.23642536]
 [-0.15876736]
 [-0.44683558]]
Cost after iteration 8000: 0.260161
[[ 2.44838003]
 [-0.16984011]
 [-0.49864338]]
Cost after iteration 9000: 0.238601
[[ 2.64432672]
 [-0.17895857]
 [-0.5466793 ]]
Cost after iteration 10000: 0.220017
[[ 2.82623826]
 [-0.18652404]
 [-0.59138916]]
Cost after iteration 11000: 0.203873
[[ 2.99577992]
 [-0.1928464 ]
 [-0.63315355]]
Cost after it

Cost after iteration 100000: 0.023709
[[ 7.48606855]
 [-0.23233621]
 [-1.75607239]]
Cost after iteration 101000: 0.023467
[[ 7.50677346]
 [-0.23230354]
 [-1.76127134]]
Cost after iteration 102000: 0.023231
[[ 7.52727114]
 [-0.2322709 ]
 [-1.76641819]]
Cost after iteration 103000: 0.022999
[[ 7.54756565]
 [-0.23223832]
 [-1.77151397]]
Cost after iteration 104000: 0.022771
[[ 7.56766092]
 [-0.23220579]
 [-1.77655966]]
Cost after iteration 105000: 0.022548
[[ 7.5875608 ]
 [-0.23217334]
 [-1.78155623]]
Cost after iteration 106000: 0.022330
[[ 7.60726899]
 [-0.23214097]
 [-1.78650461]]
Cost after iteration 107000: 0.022115
[[ 7.62678912]
 [-0.23210869]
 [-1.79140572]]
Cost after iteration 108000: 0.021905
[[ 7.6461247 ]
 [-0.23207651]
 [-1.79626043]]
Cost after iteration 109000: 0.021698
[[ 7.66527915]
 [-0.23204442]
 [-1.8010696 ]]
Cost after iteration 110000: 0.021495
[[ 7.6842558 ]
 [-0.23201245]
 [-1.80583408]]
Cost after iteration 111000: 0.021296
[[ 7.70305787]
 [-0.23198059]
 [-1.810

Cost after iteration 198000: 0.011763
[[ 8.89944941]
 [-0.22979741]
 [-2.11079306]]
Cost after iteration 199000: 0.011703
[[ 8.90981237]
 [-0.22977853]
 [-2.11339241]]
Cost after iteration 200000: 0.011643
[[ 8.92012254]
 [-0.22975977]
 [-2.11597849]]
Cost after iteration 201000: 0.011584
[[ 8.93038045]
 [-0.22974112]
 [-2.11855145]]
Cost after iteration 202000: 0.011525
[[ 8.94058662]
 [-0.22972259]
 [-2.1211114 ]]
Cost after iteration 203000: 0.011467
[[ 8.95074157]
 [-0.22970416]
 [-2.12365849]]
Cost after iteration 204000: 0.011410
[[ 8.96084581]
 [-0.22968585]
 [-2.12619283]]
Cost after iteration 205000: 0.011353
[[ 8.97089983]
 [-0.22966764]
 [-2.12871456]]
Cost after iteration 206000: 0.011296
[[ 8.98090413]
 [-0.22964954]
 [-2.1312238 ]]
Cost after iteration 207000: 0.011241
[[ 8.99085921]
 [-0.22963155]
 [-2.13372067]]
Cost after iteration 208000: 0.011185
[[ 9.00076552]
 [-0.22961367]
 [-2.13620529]]
Cost after iteration 209000: 0.011131
[[ 9.01062356]
 [-0.22959589]
 [-2.138

Cost after iteration 296000: 0.007804
[[ 9.7239922 ]
 [-0.22837185]
 [-2.31754461]]
Cost after iteration 297000: 0.007777
[[ 9.73088732]
 [-0.22836072]
 [-2.31927296]]
Cost after iteration 298000: 0.007750
[[ 9.73775893]
 [-0.22834964]
 [-2.32099542]]
Cost after iteration 299000: 0.007724
[[ 9.7446072 ]
 [-0.22833861]
 [-2.32271201]]
Cost after iteration 300000: 0.007698
[[ 9.75143229]
 [-0.22832764]
 [-2.32442278]]
Cost after iteration 301000: 0.007672
[[ 9.75823434]
 [-0.22831672]
 [-2.32612777]]
Cost after iteration 302000: 0.007646
[[ 9.76501351]
 [-0.22830584]
 [-2.32782701]]
Cost after iteration 303000: 0.007620
[[ 9.77176995]
 [-0.22829502]
 [-2.32952055]]
Cost after iteration 304000: 0.007595
[[ 9.77850382]
 [-0.22828425]
 [-2.33120843]]
Cost after iteration 305000: 0.007569
[[ 9.78521527]
 [-0.22827353]
 [-2.33289067]]
Cost after iteration 306000: 0.007544
[[ 9.79190444]
 [-0.22826286]
 [-2.33456732]]
Cost after iteration 307000: 0.007519
[[ 9.79857148]
 [-0.22825224]
 [-2.336

Cost after iteration 394000: 0.005834
[[10.30755217]
 [-0.22748433]
 [-2.46379005]]
Cost after iteration 395000: 0.005819
[[10.31271482]
 [-0.22747698]
 [-2.46508357]]
Cost after iteration 396000: 0.005804
[[10.31786425]
 [-0.22746967]
 [-2.46637379]]
Cost after iteration 397000: 0.005790
[[10.32300053]
 [-0.22746238]
 [-2.4676607 ]]
Cost after iteration 398000: 0.005775
[[10.32812374]
 [-0.22745512]
 [-2.46894434]]
Cost after iteration 399000: 0.005760
[[10.33323392]
 [-0.22744788]
 [-2.4702247 ]]
Cost after iteration 400000: 0.005745
[[10.33833116]
 [-0.22744068]
 [-2.47150182]]
Cost after iteration 401000: 0.005731
[[10.34341552]
 [-0.2274335 ]
 [-2.47277571]]
Cost after iteration 402000: 0.005716
[[10.34848706]
 [-0.22742634]
 [-2.47404638]]
Cost after iteration 403000: 0.005702
[[10.35354584]
 [-0.22741922]
 [-2.47531385]]
Cost after iteration 404000: 0.005688
[[10.35859194]
 [-0.22741212]
 [-2.47657814]]
Cost after iteration 405000: 0.005673
[[10.36362541]
 [-0.22740505]
 [-2.477

Cost after iteration 492000: 0.004657
[[10.7593616 ]
 [-0.22687598]
 [-2.57697633]]
Cost after iteration 493000: 0.004648
[[10.76348628]
 [-0.22687075]
 [-2.57800948]]
Cost after iteration 494000: 0.004638
[[10.76760252]
 [-0.22686553]
 [-2.57904051]]
Cost after iteration 495000: 0.004629
[[10.77171033]
 [-0.22686033]
 [-2.58006943]]
Cost after iteration 496000: 0.004619
[[10.77580977]
 [-0.22685514]
 [-2.58109626]]
Cost after iteration 497000: 0.004610
[[10.77990086]
 [-0.22684998]
 [-2.58212098]]
Cost after iteration 498000: 0.004600
[[10.78398364]
 [-0.22684482]
 [-2.58314363]]
Cost after iteration 499000: 0.004591
[[10.78805814]
 [-0.22683969]
 [-2.58416419]]
Cost after iteration 500000: 0.004582
[[10.79212439]
 [-0.22683457]
 [-2.58518269]]
Cost after iteration 501000: 0.004572
[[10.79618243]
 [-0.22682946]
 [-2.58619913]]
Cost after iteration 502000: 0.004563
[[10.8002323 ]
 [-0.22682437]
 [-2.58721352]]
Cost after iteration 503000: 0.004554
[[10.80427401]
 [-0.2268193 ]
 [-2.588

Cost after iteration 591000: 0.003868
[[11.13143737]
 [-0.22642675]
 [-2.67016352]]
Cost after iteration 592000: 0.003861
[[11.13486517]
 [-0.22642282]
 [-2.67102193]]
Cost after iteration 593000: 0.003855
[[11.13828714]
 [-0.2264189 ]
 [-2.67187887]]
Cost after iteration 594000: 0.003848
[[11.14170328]
 [-0.226415  ]
 [-2.67273435]]
Cost after iteration 595000: 0.003842
[[11.14511362]
 [-0.22641111]
 [-2.67358838]]
Cost after iteration 596000: 0.003835
[[11.14851817]
 [-0.22640722]
 [-2.67444096]]
Cost after iteration 597000: 0.003829
[[11.15191696]
 [-0.22640335]
 [-2.67529209]]
Cost after iteration 598000: 0.003822
[[11.15531001]
 [-0.22639948]
 [-2.67614178]]
Cost after iteration 599000: 0.003816
[[11.15869734]
 [-0.22639563]
 [-2.67699004]]
Cost after iteration 600000: 0.003809
[[11.16207895]
 [-0.22639179]
 [-2.67783686]]
Cost after iteration 601000: 0.003803
[[11.16545489]
 [-0.22638796]
 [-2.67868226]]
Cost after iteration 602000: 0.003796
[[11.16882515]
 [-0.22638413]
 [-2.679

Cost after iteration 690000: 0.003307
[[11.44522578]
 [-0.22608304]
 [-2.74873696]]
Cost after iteration 691000: 0.003302
[[11.44815787]
 [-0.22607997]
 [-2.74947109]]
Cost after iteration 692000: 0.003298
[[11.45108568]
 [-0.22607692]
 [-2.75020416]]
Cost after iteration 693000: 0.003293
[[11.45400922]
 [-0.22607387]
 [-2.75093616]]
Cost after iteration 694000: 0.003288
[[11.45692851]
 [-0.22607082]
 [-2.75166709]]
Cost after iteration 695000: 0.003283
[[11.45984356]
 [-0.22606779]
 [-2.75239696]]
Cost after iteration 696000: 0.003278
[[11.46275439]
 [-0.22606476]
 [-2.75312577]]
Cost after iteration 697000: 0.003274
[[11.46566099]
 [-0.22606174]
 [-2.75385352]]
Cost after iteration 698000: 0.003269
[[11.46856339]
 [-0.22605872]
 [-2.75458022]]
Cost after iteration 699000: 0.003264
[[11.4714616 ]
 [-0.22605571]
 [-2.75530587]]
Cost after iteration 700000: 0.003259
[[11.47435563]
 [-0.22605271]
 [-2.75603047]]
Cost after iteration 701000: 0.003255
[[11.4772455 ]
 [-0.22604972]
 [-2.756

Cost after iteration 789000: 0.002888
[[11.71651804]
 [-0.22581068]
 [-2.81665871]]
Cost after iteration 790000: 0.002885
[[11.71907952]
 [-0.22580821]
 [-2.81729996]]
Cost after iteration 791000: 0.002881
[[11.72163772]
 [-0.22580575]
 [-2.8179404 ]]
Cost after iteration 792000: 0.002877
[[11.72419268]
 [-0.2258033 ]
 [-2.81858002]]
Cost after iteration 793000: 0.002874
[[11.72674438]
 [-0.22580084]
 [-2.81921883]]
Cost after iteration 794000: 0.002870
[[11.72929283]
 [-0.2257984 ]
 [-2.81985683]]
Cost after iteration 795000: 0.002866
[[11.73183806]
 [-0.22579596]
 [-2.82049401]]
Cost after iteration 796000: 0.002863
[[11.73438006]
 [-0.22579352]
 [-2.82113039]]
Cost after iteration 797000: 0.002859
[[11.73691884]
 [-0.22579109]
 [-2.82176595]]
Cost after iteration 798000: 0.002855
[[11.73945441]
 [-0.22578867]
 [-2.82240072]]
Cost after iteration 799000: 0.002852
[[11.74198678]
 [-0.22578625]
 [-2.82303468]]
Cost after iteration 800000: 0.002848
[[11.74451596]
 [-0.22578383]
 [-2.823

Cost after iteration 888000: 0.002563
[[11.95545134]
 [-0.22558895]
 [-2.87647147]]
Cost after iteration 889000: 0.002560
[[11.95772529]
 [-0.22558692]
 [-2.87704068]]
Cost after iteration 890000: 0.002558
[[11.95999666]
 [-0.22558489]
 [-2.87760924]]
Cost after iteration 891000: 0.002555
[[11.96226546]
 [-0.22558287]
 [-2.87817717]]
Cost after iteration 892000: 0.002552
[[11.96453169]
 [-0.22558085]
 [-2.87874444]]
Cost after iteration 893000: 0.002549
[[11.96679537]
 [-0.22557883]
 [-2.87931108]]
Cost after iteration 894000: 0.002546
[[11.96905649]
 [-0.22557682]
 [-2.87987708]]
Cost after iteration 895000: 0.002543
[[11.97131507]
 [-0.22557481]
 [-2.88044244]]
Cost after iteration 896000: 0.002540
[[11.9735711 ]
 [-0.22557281]
 [-2.88100716]]
Cost after iteration 897000: 0.002537
[[11.9758246 ]
 [-0.2255708 ]
 [-2.88157125]]
Cost after iteration 898000: 0.002535
[[11.97807557]
 [-0.22556881]
 [-2.8821347 ]]
Cost after iteration 899000: 0.002532
[[11.98032402]
 [-0.22556681]
 [-2.882

Cost after iteration 987000: 0.002304
[[12.16892135]
 [-0.22540455]
 [-2.92990443]]
Cost after iteration 988000: 0.002302
[[12.17096575]
 [-0.22540285]
 [-2.93041613]]
Cost after iteration 989000: 0.002299
[[12.17300805]
 [-0.22540114]
 [-2.93092731]]
Cost after iteration 990000: 0.002297
[[12.17504828]
 [-0.22539944]
 [-2.93143796]]
Cost after iteration 991000: 0.002295
[[12.17708644]
 [-0.22539775]
 [-2.9319481 ]]
Cost after iteration 992000: 0.002292
[[12.17912252]
 [-0.22539605]
 [-2.93245772]]
Cost after iteration 993000: 0.002290
[[12.18115654]
 [-0.22539436]
 [-2.93296682]]
Cost after iteration 994000: 0.002288
[[12.1831885 ]
 [-0.22539267]
 [-2.93347541]]
Cost after iteration 995000: 0.002285
[[12.1852184 ]
 [-0.22539099]
 [-2.93398348]]
Cost after iteration 996000: 0.002283
[[12.18724625]
 [-0.22538931]
 [-2.93449104]]
Cost after iteration 997000: 0.002281
[[12.18927204]
 [-0.22538763]
 [-2.93499808]]
Cost after iteration 998000: 0.002279
[[12.19129579]
 [-0.22538595]
 [-2.935

In [10]:
#Try a Test Value
print ("Considering new situation [1, 0, 0] -> ?: ")
test = np.array([1, 0, 0])
yhat = sigmoid(np.dot(w.T,test)+b)
print (yhat)
print (np.where(yhat>0.5,1,0))
print (w)
print (b)

print ('')
print ("Considering new situation [0, 0, 0] -> ?: ")
test = np.array([0, 0, 0])
yhat = sigmoid(np.dot(w.T,test)+b)
print (yhat)
print (np.where(yhat>0.5,1,0))
print (w)
print (b)

Considering new situation [1, 0, 0] -> ?: 
[0.99990474]
[1]
[[12.19533516]
 [-0.2253826 ]
 [-2.93651563]]
-2.936515632097113

Considering new situation [0, 0, 0] -> ?: 
[0.0503777]
[0]
[[12.19533516]
 [-0.2253826 ]
 [-2.93651563]]
-2.936515632097113
