In [1]:
#Imports
import numpy as np

In [2]:
#Load Training Data
#X
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]]).T

#Y
training_set_outputs = np.array([[0, 1, 1, 0]])


#print (training_set_inputs.shape)
#print (training_set_inputs)
#print (training_set_outputs.shape)
#print (training_set_outputs)

In [3]:
#Initialization Function (Weights and Bias)
def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    w = np.zeros((dim,1))
    b = 0

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b


In [4]:
#Activation Function (Sigmoid in this case)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [5]:
def forward_pass_and_backprop(w, b, X, Y):
    """
    Forward pass cost function

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    # Compute Activation
    A = sigmoid(np.dot(w.T,X)+b)                
    #print (A)
    
    # Compute loss (The difference between the desired output and the predicted output)
    # Then sum + extra to produce cost value
    cost = -1 / m * np.sum(Y*np.log(A)+(1-Y)*np.log(1-A), axis = 1, keepdims = True)
    
        
    # BACKWARD PROPAGATION (TO FIND GRAD)
    dw = 1 / m * np.dot(X,(A-Y).T)
    db = 1 / m * np.sum(A-Y)
    
    """
    print ("shape of A = " + str(A.shape))
    print ("shape of Y = " + str(Y.shape))
    print ("m = " + str(m))
    print ("shape of dw = " + str(dw.shape))
    print ("shape of w = " + str(w.shape))
    """
    
    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [6]:
#Unit Test For forward_pass_and_backprop
#cost = 5.801545319394553
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
grads, cost = forward_pass_and_backprop(w, b, X, Y)
print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))
print ("cost = " + str(cost))

dw = [[0.99845601]
 [2.39507239]]
db = 0.001455578136784208
cost = 5.801545319394553


In [7]:
# Train the neural network adjusting the synaptic weights after each epoch
def train(X, Y, number_of_training_iterations, w, b):
        
        print_cost = True
        costs = []
        
        print (w)
        
        for iteration in range(number_of_training_iterations):
        
            # Pass the training set through our neural network (a single neuron) and compute cost
            grads, cost = forward_pass_and_backprop(w, b, X, Y)

            # Retrieve derivatives from grads
            dw = grads["dw"]
            db = grads["db"]

            # update weights
            w = w - learning_rate * dw
            b = b - learning_rate * db
            
            
            # Record the costs
            if iteration % 100 == 0:
                costs.append(cost)
        
            # Print the cost every 100 training iterations
            if print_cost and iteration % 100 == 0:
                print ("Cost after iteration %i: %f" %(iteration, cost))
                print (w)
            
            #print (w.T)
                        
        return w,b


In [8]:
#Train the Network (Model)

# Base Hyperparameters
number_of_training_iterations = 10000
learning_rate = 0.002

# initialize parameters
X = training_set_inputs
Y = training_set_outputs
w, b = initialize_with_zeros(X.shape[0])

# Train
w,b = train(X, Y, number_of_training_iterations, w, b)





[[0.]
 [0.]
 [0.]]
Cost after iteration 0: 0.693147
[[0.0005]
 [0.    ]
 [0.    ]]
Cost after iteration 100: 0.680942
[[ 0.04988524]
 [-0.00030046]
 [-0.00060343]]
Cost after iteration 200: 0.669274
[[ 0.09811603]
 [-0.00113852]
 [-0.00229638]]
Cost after iteration 300: 0.658070
[[ 0.14527879]
 [-0.00243621]
 [-0.00493533]]
Cost after iteration 400: 0.647273
[[ 0.19145079]
 [-0.00412495]
 [-0.00839362]]
Cost after iteration 500: 0.636838
[[ 0.23670099]
 [-0.00614452]
 [-0.01255964]]
Cost after iteration 600: 0.626728
[[ 0.28109087]
 [-0.00844216]
 [-0.01733526]]
Cost after iteration 700: 0.616915
[[ 0.32467521]
 [-0.01097173]
 [-0.02263426]]
Cost after iteration 800: 0.607374
[[ 0.36750285]
 [-0.01369295]
 [-0.028381  ]]
Cost after iteration 900: 0.598087
[[ 0.40961737]
 [-0.01657068]
 [-0.03450916]]
Cost after iteration 1000: 0.589037
[[ 0.45105767]
 [-0.01957435]
 [-0.04096066]]
Cost after iteration 1100: 0.580211
[[ 0.49185856]
 [-0.02267737]
 [-0.04768467]]
Cost after iteration 120

In [12]:
#Try a Test Value
print ("Considering new situation [1, 0, 0] -> ?: ")
test = np.array([1, 0, 0])
yhat = sigmoid(np.dot(w.T,test)+b)
print (yhat)
print (np.where(yhat>0.5,1,0))
print (w)

print ('')
print ("Considering new situation [0, 0, 0] -> ?: ")
test = np.array([0, 0, 0])
yhat = sigmoid(np.dot(w.T,test)+b)
print (yhat)
print (np.where(yhat>0.5,1,0))
print (w)

Considering new situation [1, 0, 0] -> ?: 
[0.90332406]
[1]
[[ 2.82606278]
 [-0.18651714]
 [-0.59134598]]

Considering new situation [0, 0, 0] -> ?: 
[0.35632608]
[0]
[[ 2.82606278]
 [-0.18651714]
 [-0.59134598]]
