In [29]:
import torch
import torch.nn as nn



In [6]:
x = torch.randn(3, requires_grad=True)
print (x)

tensor([-0.1061, -0.2648, -1.2205], requires_grad=True)


In [9]:
y = 1
print (y)

1


In [11]:
z = x * y
print (z)

tensor([-0.1061, -0.2648, -1.2205], grad_fn=<MulBackward>)


In [13]:
zz = z * z
print (zz)

tensor([0.0113, 0.0701, 1.4897], grad_fn=<ThMulBackward>)


In [14]:
print(x.grad)

None


In [24]:
x = torch.randn(3,3, requires_grad=True)

y = x * 2

print(x)
print(y)

tensor([[ 0.3115, -1.5271,  0.6817],
        [-0.4059,  1.3599, -0.5162],
        [ 0.5175,  0.5136, -1.4213]], requires_grad=True)
tensor([[ 0.6229, -3.0541,  1.3633],
        [-0.8118,  2.7198, -1.0324],
        [ 1.0350,  1.0272, -2.8426]], grad_fn=<MulBackward>)


In [27]:
#gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward()

print(x.grad)

RuntimeError: grad can be implicitly created only for scalar outputs

In [39]:
m = nn.Linear(20, 30, bias=False)
input = torch.randn(128, 20)
output = m(input)
print(output.size())

torch.Size([128, 30])


In [40]:
print(output)

tensor([[-0.3979, -0.9632,  0.3687,  ...,  0.3078, -0.0313, -0.3832],
        [ 0.8841, -0.0237,  0.0224,  ..., -0.4116, -0.7265,  0.6323],
        [-1.9711, -1.8030, -0.0817,  ..., -0.2703, -0.6364,  0.3381],
        ...,
        [ 0.1975, -0.8369, -0.4752,  ...,  0.3476,  0.0847,  0.1286],
        [ 0.1463, -0.2244, -0.0451,  ..., -0.1671,  0.7212,  0.1674],
        [ 0.8224,  0.8837,  0.1492,  ...,  0.0264, -0.5300,  0.0574]],
       grad_fn=<MmBackward>)


In [43]:
params = list(m.parameters())
print(len(params))       

#print(params[1])
print(params[0])
print(params[0].shape)

1
Parameter containing:
tensor([[-0.1055, -0.1876,  0.0046, -0.0772, -0.1089,  0.0276, -0.1450,  0.1895,
          0.1889, -0.0686,  0.1130,  0.0535,  0.1389, -0.0405,  0.2050, -0.2172,
          0.2120,  0.0993, -0.1854,  0.1946],
        [-0.1474,  0.0385, -0.0248,  0.2020, -0.2174, -0.1968, -0.1064,  0.0959,
          0.1565,  0.2187,  0.1670,  0.0309, -0.1159, -0.0948,  0.1068,  0.0721,
          0.1335, -0.1962,  0.0051,  0.1254],
        [ 0.0375,  0.1391, -0.0063,  0.1116,  0.0384,  0.0591,  0.1223, -0.0043,
          0.1056,  0.1578,  0.0007, -0.0063, -0.0203, -0.0166,  0.0208, -0.0298,
          0.0109, -0.1951,  0.1670,  0.1585],
        [-0.0477,  0.0804, -0.0996,  0.0258,  0.0740,  0.0806, -0.0018,  0.1688,
          0.1730,  0.1487, -0.0711, -0.0676, -0.0653, -0.0356,  0.0416,  0.1307,
         -0.0517, -0.1478, -0.2169,  0.0047],
        [-0.0029, -0.1890, -0.0073,  0.1643, -0.1134,  0.0102, -0.1514, -0.1684,
         -0.0726, -0.0770,  0.0642, -0.1711,  0.0053,  0.1334, 

In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [3]:
type(data)

list