In [1]:
import tensorflow as tf
import numpy as np
import math

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sess = tf.InteractiveSession()

In [5]:
# Some simple constants
x1 = tf.Variable(tf.truncated_normal([5],
                 mean=3, stddev=1./math.sqrt(5)))
x2 = tf.Variable(tf.truncated_normal([5],
                 mean=-1, stddev=1./math.sqrt(5)))
x3 = tf.Variable(tf.truncated_normal([5],
                 mean=0, stddev=1./math.sqrt(5)))

sess.run(tf.initialize_all_variables())

In [6]:
#Some various transofmaion functions
# Squaring makes large values extreme (but positive)
# Be careful if you have negative values
sqx2 = x2 * x2
print(x2.eval())
print(sqx2.eval())

[-1.4101932  -0.68189466 -0.70575464 -1.0552961  -0.9918436 ]
[1.9886448  0.46498033 0.4980896  1.1136497  0.9837537 ]


In [7]:
# Logarithm makes small values more pronounced (and negative)
# Be careful that your algorithm can handle negative numbers
logx1 = tf.log(x1)
print(x1.eval())
print(logx1.eval())

[2.7462828 2.9636228 3.2085812 3.447855  2.8924775]
[1.0102483 1.0864124 1.1658288 1.2377523 1.0621134]


In [8]:
# "sigmoid" is a common transformation in deep learning
# Extreme values get flattened to +1 or 0
# Inputs closer to zero stay similar, sigmoid(0) = 0.5
sigx3 = tf.sigmoid(x3)
print(x3.eval())
print(sigx3.eval())

[-0.577517   -0.21289216  0.05287118  0.02893063 -0.2722765 ]
[0.35950413 0.44697705 0.51321477 0.5072322  0.43234828]


In [20]:
# We linearly combine multiple inputs, then transform
w1 = tf.constant(0.1)
w2 = tf.constant(0.2)
sess.run(tf.initialize_all_variables())
n1 = tf.sigmoid(w1*x1 + w2*x2)
print((w1*x1).eval())
print((w2*x2).eval())
print(n1.eval())

[0.35060728 0.24993423 0.284758   0.37045273 0.28387672]
[-0.21620882 -0.2421993  -0.2644311  -0.12517658 -0.17034416]
[0.53354913 0.5019337  0.50508153 0.56101346 0.5283527 ]
